### ISSUE TITLE
[Issue]TinyFecVPN Can't Connect With MIMIC : Connection Destroyed

### ISSUE THREAD

**Issue by Handsome1080P** [hack3ric/mimic#3] opened 2024-04-18 08:06 UTC
# Test environment,Vmware ESXI Based.
VM OS: Debian 12 Full Updated.
VM1: 192.168.3.1 eth3
VM2: 192.168.3.2 eth3

### Commands:
**Server Side,VM2**

`./tinyvpn -s -l 0.0.0.0:8001 --sub-net 192.168.55.1 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10`
` mimic run -f local=192.168.3.2:8001 eth3`

**Client Side,VM1**
`./tinyvpn -c -r 192.168.3.2:8001 --sub-net 192.168.55.2 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10`
`mimic run -f remote=192.168.3.2:8001 eth3`

### TEST
**On Client VM1 test,cant ping server.And tinyfecvpn did't receive any incoming connections.**

> root@VM-4:~# ping 192.168.55.1
> PING 192.168.55.1 (192.168.55.1) 56(84) bytes of data.

> root@VM-4:~# ./tinyvpn -c -r 192.168.3.2:8001 --sub-net 192.168.55.2 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10
[2024-04-18 03:51:03][INFO]argc=19 ./tinyvpn -c -r 192.168.3.2:8001 --sub-net 192.168.55.2 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10
[2024-04-18 03:51:03][INFO]parsing address: 192.168.3.2:8001
[2024-04-18 03:51:03][INFO]its an ipv4 adress
[2024-04-18 03:51:03][INFO]ip_address is {192.168.3.2}, port is {8001}
[2024-04-18 03:51:03][INFO]sub_net 192.168.55.2
[2024-04-18 03:51:03][INFO]tun_dev=tun1
[2024-04-18 03:51:03][INFO]decode-buf=10240
[2024-04-18 03:51:03][INFO]jitter_min=0 jitter_max=0 output_interval_min=10 output_interval_max=10 fec_timeout=8 fec_mtu=1250 fec_queue_len=200 fec_mode=0
[2024-04-18 03:51:03][INFO]fec_str=20:10
[2024-04-18 03:51:03][INFO]fec_inner_parameter=1:10,2:10,3:10,4:10,5:10,6:10,7:10,8:10,9:10,10:10,11:10,12:10,13:10,14:10,15:10,16:10,17:10,18:10,19:10,20:10
[2024-04-18 03:51:03][INFO]using interface tun1

**MIMIC Client Logs**

> Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021
 Info ingress: connection established: 192.168.3.2:8001 => 192.168.3.1:46021

**On server side,no tinyfecvpn did't recieve any incoming connections too.**

> root@VM-5:~# ./tinyvpn -s -l 0.0.0.0:8001 --sub-net 192.168.55.1 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10[2024-04-18 03:51:17][INFO]argc=19 ./tinyvpn -s -l 0.0.0.0:8001 --sub-net 192.168.55.1 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10
[2024-04-18 03:51:17][INFO]parsing address: 0.0.0.0:8001
[2024-04-18 03:51:17][INFO]its an ipv4 adress
[2024-04-18 03:51:17][INFO]ip_address is {0.0.0.0}, port is {8001}
[2024-04-18 03:51:17][INFO]sub_net 192.168.55.1
[2024-04-18 03:51:17][INFO]tun_dev=tun1
[2024-04-18 03:51:17][INFO]decode-buf=10240
[2024-04-18 03:51:17][INFO]jitter_min=0 jitter_max=0 output_interval_min=10 output_interval_max=10 fec_timeout=8 fec_mtu=1250 fec_queue_len=200 fec_mode=0
[2024-04-18 03:51:17][INFO]fec_str=20:10
[2024-04-18 03:51:17][INFO]fec_inner_parameter=1:10,2:10,3:10,4:10,5:10,6:10,7:10,8:10,9:10,10:10,11:10,12:10,13:10,14:10,15:10,16:10,17:10,18:10,19:10,20:10
[2024-04-18 03:51:17][INFO]using interface tun1
[2024-04-18 03:51:17][INFO]now listening at 0.0.0.0:8001

**MIMIC Server Logs**

> Info ingress: connection established: 192.168.3.1:46021 => 192.168.3.2:8001
 Warn ingress: received RST: 192.168.3.1:46021 => 192.168.3.2:8001
 Warn ingress: connection destroyed: 192.168.3.1:46021 => 192.168.3.2:8001
 Warn ingress: received RST: 192.168.3.1:46021 => 192.168.3.2:8001
 Warn ingress: received RST: 192.168.3.1:46021 => 192.168.3.2:8001
 Warn ingress: received RST: 192.168.3.1:46021 => 192.168.3.2:8001
 Warn ingress: received RST: 192.168.3.1:46021 => 192.168.3.2:8001
 Warn ingress: received RST: 192.168.3.1:46021 => 192.168.3.2:8001
 Warn ingress: received RST: 192.168.3.1:46021 => 192.168.3.2:8001
 Warn ingress: received RST: 192.168.3.1:46021 => 192.168.3.2:8001

**If I remove mimic.tinyfecvpn can connect.**
**Client**

> root@VM-4:~# ping 192.168.55.1
PING 192.168.55.1 (192.168.55.1) 56(84) bytes of data.
64 bytes from 192.168.55.1: icmp_seq=1 ttl=64 time=246 ms
64 bytes from 192.168.55.1: icmp_seq=2 ttl=64 time=247 ms
64 bytes from 192.168.55.1: icmp_seq=3 ttl=64 time=246 ms
64 bytes from 192.168.55.1: icmp_seq=4 ttl=64 time=245 ms

> ./tinyvpn -c -r 192.168.3.2:8001 --sub-net 192.168.55.2 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10
[2024-04-18 03:51:03][INFO]argc=19 ./tinyvpn -c -r 192.168.3.2:8001 --sub-net 192.168.55.2 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10
[2024-04-18 03:51:03][INFO]parsing address: 192.168.3.2:8001
[2024-04-18 03:51:03][INFO]its an ipv4 adress
[2024-04-18 03:51:03][INFO]ip_address is {192.168.3.2}, port is {8001}
[2024-04-18 03:51:03][INFO]sub_net 192.168.55.2
[2024-04-18 03:51:03][INFO]tun_dev=tun1
[2024-04-18 03:51:03][INFO]decode-buf=10240
[2024-04-18 03:51:03][INFO]jitter_min=0 jitter_max=0 output_interval_min=10 output_interval_max=10 fec_timeout=8 fec_mtu=1250 fec_queue_len=200 fec_mode=0
[2024-04-18 03:51:03][INFO]fec_str=20:10
[2024-04-18 03:51:03][INFO]fec_inner_parameter=1:10,2:10,3:10,4:10,5:10,6:10,7:10,8:10,9:10,10:10,11:10,12:10,13:10,14:10,15:10,16:10,17:10,18:10,19:10,20:10
[2024-04-18 03:51:03][INFO]using interface tun1
[2024-04-18 04:01:26][INFO]connection accepted by server

**Server**

> root@VM-5:~# ./tinyvpn -s -l 192.168.3.2:8001 --sub-net 192.168.55.1 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10
[2024-04-18 03:51:28][INFO]argc=19 ./tinyvpn -s -l 192.168.3.2:8001 --sub-net 192.168.55.1 --tun-dev tun1 --sock-buf 10240 --decode-buf 10240 --mode 0 -f20:10 --timeout 8 -i 10
[2024-04-18 03:51:28][INFO]parsing address: 192.168.3.2:8001
[2024-04-18 03:51:28][INFO]its an ipv4 adress
[2024-04-18 03:51:28][INFO]ip_address is {192.168.3.2}, port is {8001}
[2024-04-18 03:51:28][INFO]sub_net 192.168.55.1
[2024-04-18 03:51:28][INFO]tun_dev=tun1
[2024-04-18 03:51:28][INFO]decode-buf=10240
[2024-04-18 03:51:28][INFO]jitter_min=0 jitter_max=0 output_interval_min=10 output_interval_max=10 fec_timeout=8 fec_mtu=1250 fec_queue_len=200 fec_mode=0
[2024-04-18 03:51:28][INFO]fec_str=20:10
[2024-04-18 03:51:28][INFO]fec_inner_parameter=1:10,2:10,3:10,4:10,5:10,6:10,7:10,8:10,9:10,10:10,11:10,12:10,13:10,14:10,15:10,16:10,17:10,18:10,19:10,20:10
[2024-04-18 03:51:28][INFO]using interface tun1
[2024-04-18 03:51:28][INFO]now listening at 192.168.3.2:8001
[2024-04-18 04:01:16][INFO]new connection from 192.168.3.1:46021

**Comment by hack3ric** [comment] 2024-04-18 09:12
I can't reproduce this using libvirt, Mimic 0.3.0 and TinyFecVPN 20230206.0 and traffic works fine. What version of Mimic did you use? I've been pushing some experimental stuff onto master branch recently that probably won't work correctly.

Besides, I suspect this is caused by some sort of firewalls, or something to do with ESXi's virtual network implementation. I am not really sure where those RSTs were coming from. Some packet capturing may help.

**Comment by Handsome1080P** [comment] 2024-04-18 15:41
Thx for your reply.I am using lastest MIMIC and lastest tinyfecvpn.I will test and capture packets latter.I didn't notice my iptables on or not.I will check it tonight.

**Comment by Handsome1080P** [comment] 2024-04-18 15:43
Info add: Debian 12 with latest release MIMIC.

**Comment by Handsome1080P** [comment] 2024-04-19 06:33
@hack3ric 
**Checked VMs firewall,not installed iptables or enabled nftable.the only difference is my env has multiple NICs.Latency is also different.**
![image](https://github.com/hack3ric/mimic/assets/13675031/e4960ba7-0c6d-4b01-ab40-f0571e35be6f)
![image](https://github.com/hack3ric/mimic/assets/13675031/8b4d2b2e-09d7-4e86-92b2-5efe1384a432)
![image](https://github.com/hack3ric/mimic/assets/13675031/bac33169-b90b-43f3-9183-bb14879902ae)
![image](https://github.com/hack3ric/mimic/assets/13675031/9994e165-c4e6-4d9d-8502-bde035413baf)
**Route Table Main**
![image](https://github.com/hack3ric/mimic/assets/13675031/c63c996a-6c3c-4e1d-9d09-bb14ba53d17f)
## TEST 1
**On MAIN NIC,eth0.It works**
![image](https://github.com/hack3ric/mimic/assets/13675031/e5dbfdeb-cfdc-4845-ab0d-2f0ccbb95553)
![image](https://github.com/hack3ric/mimic/assets/13675031/5f0f43af-f7e1-4e11-84ad-c97d0e12c4f5)
![image](https://github.com/hack3ric/mimic/assets/13675031/4b6f4129-3ba2-48bd-8ed4-bf7b4322492f)
## TEST2
**On ETH2,Not Working.Can't connect.**
![image](https://github.com/hack3ric/mimic/assets/13675031/eaf4a1ba-5a52-4f28-b499-d2f6602c8d91)
![image](https://github.com/hack3ric/mimic/assets/13675031/9724aa5b-80bd-4617-adf8-d4206dee3644)
![image](https://github.com/hack3ric/mimic/assets/13675031/fbbf054f-632e-4538-9c6e-e29963425aa5)

**Comment by hack3ric** [comment] 2024-04-19 06:58
Ah, I see the problem.

Your VM-4 has IP 192.168.2.1/24, which is (in most cases) already used by the ESXi host. Change it to any other IP in the /24 range to see if it helps.

Since this isn't related to Mimic, closing.

**Closed by hack3ric** 2024-04-19 06:58 UTC

**Comment by Handsome1080P** [comment] 2024-06-01 10:31
Got how to use now.The example so simple.
